"""Add product_id to product

Revision ID: 4af8119270e1
Revises: 
Create Date: 2024-03-20 17:11:57.710274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af8119270e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('production_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.create_unique_constraint('unique_product_product_id', ['product_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False, server_default='temp_name'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('unique_product_product_id', type_='unique')
        batch_op.drop_column('description')
        batch_op.drop_column('location')
        batch_op.drop_column('production_date')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
