"""Add courier profile tables

Revision ID: 155a9f8f674c
Revises: 57b8fdaf8e4c
Create Date: 2025-12-03 21:21:02.500123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155a9f8f674c'
down_revision = '57b8fdaf8e4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courier_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('profile_photo', sa.String(length=500), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('vehicle_plate', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=True),
    sa.Column('suspension_reason', sa.String(length=500), nullable=True),
    sa.Column('current_otp', sa.String(length=6), nullable=True),
    sa.Column('otp_created_at', sa.DateTime(), nullable=True),
    sa.Column('otp_attempts', sa.Integer(), nullable=True),
    sa.Column('total_deliveries', sa.Integer(), nullable=True),
    sa.Column('successful_deliveries', sa.Integer(), nullable=True),
    sa.Column('total_checkpoints', sa.Integer(), nullable=True),
    sa.Column('on_time_deliveries', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('total_ratings', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('verified_since', sa.DateTime(), nullable=True),
    sa.Column('total_blockchain_records', sa.Integer(), nullable=True),
    sa.Column('last_blockchain_tx', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('courier_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courier_profiles_phone'), ['phone'], unique=True)

    op.create_table('courier_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courier_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('device_info', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['courier_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courier_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courier_sessions_token'), ['token'], unique=True)

    op.create_table('courier_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('courier_profile_id', sa.Integer(), nullable=True),
    sa.Column('courier_auth_id', sa.Integer(), nullable=True),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('checkpoint_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('device_info', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('blockchain_tx_hash', sa.String(length=100), nullable=True),
    sa.Column('blockchain_block', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['shipment_checkpoints.id'], ),
    sa.ForeignKeyConstraint(['courier_auth_id'], ['courier_authorizations.id'], ),
    sa.ForeignKeyConstraint(['courier_profile_id'], ['courier_profiles.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courier_activities')
    with op.batch_alter_table('courier_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courier_sessions_token'))

    op.drop_table('courier_sessions')
    with op.batch_alter_table('courier_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courier_profiles_phone'))

    op.drop_table('courier_profiles')
    # ### end Alembic commands ###
