"""Add user_id field to users table

Revision ID: 207774a0ce45
Revises: 306409bb5cd2
Create Date: 2025-12-06 11:12:08.914431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207774a0ce45'
down_revision = '306409bb5cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               nullable=False,
               existing_server_default=sa.text("'pending'"))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               nullable=True,
               existing_server_default=sa.text("'pending'"))

    # ### end Alembic commands ###
