"""Add product_id to shipments table

Revision ID: 23fcec8785c8
Revises: 207774a0ce45
Create Date: 2025-12-06 12:11:11.093687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23fcec8785c8'
down_revision = '207774a0ce45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_shipments_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipments_product_id'))
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
