"""Add rewards system tables

Revision ID: 241694a895a3
Revises: 42ee34ab802e
Create Date: 2025-12-02 01:25:13.837665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241694a895a3'
down_revision = '42ee34ab802e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referred_id', sa.Integer(), nullable=False),
    sa.Column('referral_code', sa.String(length=20), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('points_awarded', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_points_earned', sa.Integer(), nullable=True),
    sa.Column('current_points', sa.Integer(), nullable=True),
    sa.Column('ctk_tokens', sa.Float(), nullable=True),
    sa.Column('tokens_converted', sa.Float(), nullable=True),
    sa.Column('tier', sa.Enum('BRONZE', 'SILVER', 'GOLD', 'PLATINUM', 'DIAMOND', name='rewardtier'), nullable=True),
    sa.Column('current_login_streak', sa.Integer(), nullable=True),
    sa.Column('longest_login_streak', sa.Integer(), nullable=True),
    sa.Column('total_verifications', sa.Integer(), nullable=True),
    sa.Column('total_referrals', sa.Integer(), nullable=True),
    sa.Column('last_daily_claim', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('point_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_rewards_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('VERIFICATION', 'FIRST_VERIFICATION', 'DAILY_LOGIN', 'LOGIN_STREAK', 'REFERRAL', 'REPORT_COUNTERFEIT', 'PROFILE_COMPLETE', 'REGISTER_PRODUCT', 'TRANSFER_PRODUCT', 'TOKEN_CONVERSION', 'REDEEM_REWARD', name='pointactiontype'), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('multiplier_applied', sa.Float(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_rewards_id'], ['user_rewards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('point_transactions')
    op.drop_table('user_rewards')
    op.drop_table('referrals')
    # ### end Alembic commands ###
