"""Add transfer status, claim tokens, and product pending transfer lock

Revision ID: 306409bb5cd2
Revises: 8565735a86a3
Create Date: 2025-12-06 01:00:39.544133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '306409bb5cd2'
down_revision = '8565735a86a3'
branch_labels = None
depends_on = None


def upgrade():
    # Create ENUM types for PostgreSQL first
    connection = op.get_bind()
    
    # Create transferstatus enum if it doesn't exist
    transferstatus = postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', 'EXPIRED', name='transferstatus', create_type=False)
    transferstatus.create(connection, checkfirst=True)
    
    # Create productstatus enum if it doesn't exist  
    productstatus = postgresql.ENUM('REGISTERED', 'IN_TRANSIT', 'DELIVERED', 'VERIFIED', 'RECALLED', 'PENDING_TRANSFER', name='productstatus', create_type=False)
    productstatus.create(connection, checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_transfer_id', sa.Integer(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('REGISTERED', 'IN_TRANSIT', 'DELIVERED', 'VERIFIED', 'RECALLED', 'PENDING_TRANSFER', name='productstatus'),
               existing_nullable=True,
               postgresql_using='status::text::productstatus')
        batch_op.create_foreign_key('fk_products_pending_transfer_id', 'transfers', ['pending_transfer_id'], ['id'])

    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('recipient_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('claim_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('claim_token_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', 'EXPIRED', name='transferstatus'), nullable=True, server_default='PENDING'))
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('responded_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transfers_claim_token'), ['claim_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfers_claim_token'))
        batch_op.drop_column('responded_at')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('status')
        batch_op.drop_column('claim_token_expires_at')
        batch_op.drop_column('claim_token')
        batch_op.drop_column('recipient_phone')
        batch_op.drop_column('recipient_email')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_products_pending_transfer_id', type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.Enum('REGISTERED', 'IN_TRANSIT', 'DELIVERED', 'VERIFIED', 'RECALLED', 'PENDING_TRANSFER', name='productstatus'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.drop_column('pending_transfer_id')
    
    # Drop ENUM types
    connection = op.get_bind()
    postgresql.ENUM(name='transferstatus').drop(connection, checkfirst=True)
    # Don't drop productstatus as it may be used by other rows

    # ### end Alembic commands ###
