"""Add courier authorization and checkpoint chain tables

Revision ID: 57b8fdaf8e4c
Revises: acaab8e0ec25
Create Date: 2025-12-03 00:50:44.740070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b8fdaf8e4c'
down_revision = 'acaab8e0ec25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courier_authorizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('authorized_by_id', sa.Integer(), nullable=False),
    sa.Column('courier_user_id', sa.Integer(), nullable=True),
    sa.Column('courier_name', sa.String(length=100), nullable=True),
    sa.Column('courier_phone', sa.String(length=20), nullable=True),
    sa.Column('auth_code', sa.String(length=20), nullable=False),
    sa.Column('can_pickup', sa.Boolean(), nullable=True),
    sa.Column('can_checkpoint', sa.Boolean(), nullable=True),
    sa.Column('can_deliver', sa.Boolean(), nullable=True),
    sa.Column('can_handoff', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('checkpoints_recorded', sa.Integer(), nullable=True),
    sa.Column('last_action_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['authorized_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['courier_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_code')
    )
    op.create_table('checkpoint_chains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('checkpoint_id', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('current_hash', sa.String(length=64), nullable=False),
    sa.Column('data_hash', sa.String(length=64), nullable=False),
    sa.Column('blockchain_hash', sa.String(length=100), nullable=True),
    sa.Column('blockchain_block', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['shipment_checkpoints.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkpoint_chains')
    op.drop_table('courier_authorizations')
    # ### end Alembic commands ###
