"""Add external recipient fields to transfers

Revision ID: a7ac75676998
Revises: 155a9f8f674c
Create Date: 2025-12-04 17:51:12.070072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7ac75676998'
down_revision = '155a9f8f674c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('recipient_address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('recipient_type', sa.String(length=50), nullable=True))
        batch_op.alter_column('to_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.alter_column('to_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('recipient_type')
        batch_op.drop_column('recipient_address')
        batch_op.drop_column('recipient_name')

    # ### end Alembic commands ###
