"""Add shipment tracking tables for P2P delivery

Revision ID: acaab8e0ec25
Revises: 241694a895a3
Create Date: 2025-12-02 03:18:39.233007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acaab8e0ec25'
down_revision = '241694a895a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.String(length=20), nullable=False),
    sa.Column('tracking_pin', sa.String(length=10), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_name', sa.String(length=100), nullable=False),
    sa.Column('receiver_email', sa.String(length=120), nullable=True),
    sa.Column('receiver_phone', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('package_type', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.String(length=20), nullable=True),
    sa.Column('dimensions', sa.String(length=50), nullable=True),
    sa.Column('declared_value', sa.Float(), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('pickup_address', sa.Text(), nullable=False),
    sa.Column('pickup_city', sa.String(length=100), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=False),
    sa.Column('delivery_city', sa.String(length=100), nullable=True),
    sa.Column('sender_photo_url', sa.String(length=500), nullable=True),
    sa.Column('sender_photo_ipfs_hash', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'PICKED_UP', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CONFIRMED', 'CANCELLED', name='shipmentstatus'), nullable=False),
    sa.Column('current_handler_id', sa.Integer(), nullable=True),
    sa.Column('blockchain_hash', sa.String(length=100), nullable=True),
    sa.Column('blockchain_block', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_handler_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id')
    )
    op.create_table('delivery_proofs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('receiver_name', sa.String(length=100), nullable=True),
    sa.Column('receiver_relationship', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('photo_ipfs_hash', sa.String(length=100), nullable=True),
    sa.Column('signature_data', sa.Text(), nullable=True),
    sa.Column('condition_notes', sa.Text(), nullable=True),
    sa.Column('blockchain_hash', sa.String(length=100), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id')
    )
    op.create_table('shipment_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('handler_id', sa.Integer(), nullable=True),
    sa.Column('handler_name', sa.String(length=100), nullable=True),
    sa.Column('action', sa.Enum('CREATED', 'PICKED_UP', 'CHECKPOINT', 'HANDED_OFF', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CONFIRMED', name='checkpointaction'), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('photo_ipfs_hash', sa.String(length=100), nullable=True),
    sa.Column('blockchain_hash', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['handler_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_checkpoints')
    op.drop_table('delivery_proofs')
    op.drop_table('shipments')
    # ### end Alembic commands ###
